package HC;

import Clases.Funciones_AD;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import Dialogos.HCDiag.Dmedicamentos;
import Dialogos.HCDiag.Mostrarmed;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import Clases.Save;
import entity.PypAdmAsistCon;
import java.text.SimpleDateFormat;
import java.util.Date;
import Clases.Actualizar;
import Clases.CargarordenesM;

public class Medicamentos extends javax.swing.JPanel {

    Clases.Cmedicamentos med = new Clases.Cmedicamentos();
    Dialogos.HCDiag.Mostrarmed mosmed;
    private PypAdmAsistCon pypAdmAsistCon;
    Funciones_AD Funciones = new Funciones_AD();
    int row;
    Save sav = new Save();
    Object datos[][];
    public static DefaultTableModel modelo;
    String id, dosis, cantidad, dosisu, via, administracion, fc, fh;
    Actualizar act = new Actualizar();
    CargarordenesM tab = new CargarordenesM();

    public Medicamentos(PypAdmAsistCon pypAdmAsistCon) {
        initComponents();
        this.pypAdmAsistCon = pypAdmAsistCon;
        cargar();
        Tablamedi.addMouseListener(new MouseAdapter() {
        });
    }

    /**
     * This method is called frordenesm within the constructor to initialize the
     * form. WARNING: Do NOT motivocdify this code. The content of this method
     * is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablamedi = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPopupMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/clip_board.png"))); // NOI18N
        jMenuItem1.setText("Ver");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseReleased(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(408, 297));
        setMinimumSize(new java.awt.Dimension(408, 297));
        setPreferredSize(new java.awt.Dimension(408, 297));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Medicamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        Tablamedi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tablamedi.setComponentPopupMenu(jPopupMenu1);
        Tablamedi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tablamedi.setFocusable(false);
        Tablamedi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TablamediMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Tablamedi);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/añardirc1.png"))); // NOI18N
        jButton1.setToolTipText("Añadir Medicamento");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.setPreferredSize(new java.awt.Dimension(43, 40));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/añadirc2.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/quitarc1.png"))); // NOI18N
        jButton3.setToolTipText("Quitar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusable(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/quitarc2.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/1389649412_Capsule.png"))); // NOI18N
        jLabel1.setText("Medicamentos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Seleccione el medicamento y presione clic derecho para ver mas.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        if (pypAdmAsistCon.getIdAgend().getIdPrograma().getId() == 3) {
            HC.Adulto.jLabel4.setText("Añadir medicamento");
        } else {
            if (pypAdmAsistCon.getIdAgend().getIdPrograma().getId() == 9) {
                HC.Controlprenatal.jLabel4.setText("Añadir medicamento");
            }
        }
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        if (pypAdmAsistCon.getIdAgend().getIdPrograma().getId() == 3) {
            HC.Adulto.jLabel4.setText("...");
        } else {
            if (pypAdmAsistCon.getIdAgend().getIdPrograma().getId() == 9) {
                HC.Controlprenatal.jLabel4.setText("...");
            }
        }
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        if (pypAdmAsistCon.getIdAgend().getIdPrograma().getId() == 3) {
            HC.Adulto.jLabel4.setText("Quitar medicamento");
        } else {
            if (pypAdmAsistCon.getIdAgend().getIdPrograma().getId() == 9) {
                HC.Controlprenatal.jLabel4.setText("Quitar medicamento");
            }
        }
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        if (pypAdmAsistCon.getIdAgend().getIdPrograma().getId() == 3) {
            HC.Adulto.jLabel4.setText("...");
        } else {
            if (pypAdmAsistCon.getIdAgend().getIdPrograma().getId() == 9) {
                HC.Controlprenatal.jLabel4.setText("...");
            }
        }
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        quitarrgistro();
    }//GEN-LAST:event_jButton3MouseReleased

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        final Dmedicamentos medi = new Dmedicamentos((Frame) SwingUtilities.getWindowAncestor(this), true);
        medi.jButton2.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                if (medi.jTextField2.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "La dosis a aplicar no puede estar vacia");
                    medi.jTextField2.requestFocus();
                } else {
                    if (medi.jComboBox1.getSelectedIndex() == -1) {
                        JOptionPane.showMessageDialog(null, "Debe seleccionar una unidad para la dosis");
                        medi.jTextField2.requestFocus();
                    } else {
                        if (medi.jComboBox2.getSelectedIndex() == -1) {
                            JOptionPane.showMessageDialog(null, "Debe seleccionar una via de administracion");
                            medi.jTextField2.requestFocus();
                        } else {
                            if (medi.jTextField3.getText().equals("")) {
                                JOptionPane.showMessageDialog(null, "La cantidad de suministro no puede ser nula");
                                medi.jTextField3.requestFocus();
                            } else {
                                Agregar_Registro(medi.Tmedicamentos.getValueAt(medi.Tmedicamentos.getSelectedRow(), 0).toString(),
                                        medi.Tmedicamentos.getValueAt(medi.Tmedicamentos.getSelectedRow(), 1).toString(),
                                        medi.jTextField2.getText(),
                                        medi.jComboBox1.getSelectedItem().toString(),
                                        medi.jComboBox2.getSelectedItem().toString(),
                                        medi.jTextArea1.getText().toString(),
                                        medi.jTextField3.getText().toString(),
                                        "1"
                                );
                                medi.dispose();
                                id = String.valueOf(medi.Tmedicamentos.getSelectedRow());
                                dosis = medi.jTextField2.getText().toString();
                                cantidad = medi.jTextField3.getText().toString();
                                dosisu = medi.jComboBox1.getSelectedItem().toString();
                                via = medi.jComboBox2.getSelectedItem().toString();
                                administracion = medi.jTextArea1.getText().toString();
                            }
                        }
                    }
                }
            }
        });
        medi.setVisible(true);
    }//GEN-LAST:event_jButton1MouseReleased

    private void jMenuItem1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseReleased
        mosmed = new Mostrarmed((Frame) SwingUtilities.getWindowAncestor(this), true);
        mosmed.jTextArea1.setText(Tablamedi.getValueAt(row, 1).toString());
        mosmed.jLabel3.setText(Tablamedi.getValueAt(row, 2).toString() + " - " + Tablamedi.getValueAt(row, 3).toString());
        mosmed.jLabel7.setText(Tablamedi.getValueAt(row, 4).toString());
        mosmed.jTextArea2.setText(Tablamedi.getValueAt(row, 5).toString().toUpperCase());
        mosmed.setLocationRelativeTo(null);
        mosmed.setVisible(true);

    }//GEN-LAST:event_jMenuItem1MouseReleased

    private void TablamediMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablamediMouseReleased
        row = Tablamedi.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_TablamediMouseReleased
    private void cargar() {
        getModelo();
        Tablamedi.getTableHeader().setReorderingAllowed(false);
        Tablamedi.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        Funciones_AD.setOcultarColumnas(Tablamedi, new int[]{0, 2, 3, 4, 6, 5, 7});
        Funciones_AD.setSizeColumnas(Tablamedi, new int[]{1}, new int[]{650});
        Object a[][];
        a = Funciones.RetornarDatos(sav.contarhc(pypAdmAsistCon.getId().toString()));
        int b = Integer.parseInt(a[0][0].toString());
        if (b != 0) {
            Object c[][] = Funciones.RetornarDatos(sav.seleccionaridhc(pypAdmAsistCon.getId().toString()));
            String d = (c[0][0].toString());
            tab.cargartablamedi(modelo, d);
        }
    }

    public void getModelo() {
        modelo = new DefaultTableModel(
                null, new String[]{"Id", "Medicamento", "dosisf", "dosisff", "viaf", "observacion", "Cantidad sum", "estado"}) {
                    Class[] types = new Class[]{
                        java.lang.String.class,
                        java.lang.String.class,
                        java.lang.String.class,
                        java.lang.String.class,
                        java.lang.String.class,
                        java.lang.String.class,
                        java.lang.String.class,
                        java.lang.String.class
                    };
                    boolean[] canEdit = new boolean[]{
                        false, false, false, false, false, false, false, false
                    };

                    @Override
                    public Class getColumnClass(int columnIndex) {
                        return types[columnIndex];
                    }

                    @Override
                    public boolean isCellEditable(int rowIndex, int colIndex) {
                        return canEdit[colIndex];
                    }
                };
        Tablamedi.setModel(modelo);
    }

    public void Agregar_Registro(String r1, String r2, String r3, String r4, String r5, String r6, String r7, String r8) {
        try {
            DefaultTableModel temp = (DefaultTableModel) Tablamedi.getModel();
            Object nuevo[] = {r1, r2, r3, r4, r5, r6, r7, r8};
            temp.addRow(nuevo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, " :(  " + e.getMessage());
        }
    }

    public void quitarrgistro() {
        if (modelo.getRowCount() > 0 && Tablamedi.getSelectedRow() > -1) {
            if (modelo.getValueAt(Tablamedi.getSelectedRow(), 7).equals("2")) {
                Object c[][] = Funciones.RetornarDatos(sav.seleccionaridhc(pypAdmAsistCon.getId().toString()));
                String d = (c[0][0].toString());
                act.actposologia(d, modelo.getValueAt(Tablamedi.getSelectedRow(), 0).toString(), modelo.getValueAt(Tablamedi.getSelectedRow(), 2).toString());
                modelo.removeRow(Tablamedi.getSelectedRow());
            } else {
                if (modelo.getRowCount() > 0 && Tablamedi.getSelectedRow() > -1) {
                    modelo.removeRow(Tablamedi.getSelectedRow());
                }
            }
        }
    }

    public void actmedicamentos() {
        Object c[][] = Funciones.RetornarDatos(sav.seleccionaridhc(pypAdmAsistCon.getId().toString()));
        String d = (c[0][0].toString());
        Date fecha = pypAdmAsistCon.getFecha();
        Date hora = pypAdmAsistCon.getHora();
        String patronh = "HH:mm:ss";
        String patron = "yyyy-MM-dd ";
        SimpleDateFormat formato = new SimpleDateFormat(patron);
        SimpleDateFormat formatoh = new SimpleDateFormat(patronh);
        fc = formato.format(fecha);
        fh = formatoh.format(hora);
        for (int i = 0; i < modelo.getRowCount(); i++) {
            if (modelo.getValueAt(i, 7).equals("1")) {
                modelo.setValueAt("2", i, 7);
                sav.newposo(d, modelo.getValueAt(i, 0).toString(), modelo.getValueAt(i, 2).toString(),
                        modelo.getValueAt(i, 6).toString(), modelo.getValueAt(i, 3).toString(),
                        modelo.getValueAt(i, 4).toString(), modelo.getValueAt(i, 5).toString().toUpperCase(),
                        pypAdmAsistCon.getIdControlPro().getIdProfesional().getId().toString(), fc + fh, modelo.getValueAt(i, 7).toString());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTable Tablamedi;
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton3;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JMenuItem jMenuItem1;
    javax.swing.JPanel jPanel1;
    javax.swing.JPopupMenu jPopupMenu1;
    javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
