/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Entidades.PypAdmProgramas;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IdlhDeveloper
 */
public class A_Programas extends javax.swing.JDialog {
Clases.Declaraciones_AD  Declaraciones = new Clases.Declaraciones_AD();
Clases.Funciones_AD Funciones_AD = new Clases.Funciones_AD();
    /**
     * Creates new form A_Programas
     */
    public A_Programas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CrearModelo();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tabla.setSelectionForeground(new java.awt.Color(102, 102, 102));
        tabla.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tablaMouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 370, 270);

        jPanel2.setBackground(new java.awt.Color(124, 199, 33));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Atención Administrativa");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 140, 14);

        jLabel2.setText("Gestor de hojas de vida");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 22, 290, 14);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 50);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(10, 70, 370, 20);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 50, 400, 10);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Aceptar-ok.png"))); // NOI18N
        jLabel3.setToolTipText("Aceptar");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 370, 42, 43);

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setMaximumSize(new java.awt.Dimension(156, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(156, 14));
        jLabel4.setPreferredSize(new java.awt.Dimension(156, 14));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 384, 320, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       Clear_Table1();
       Cargar_Programas();
    }//GEN-LAST:event_formWindowOpened

    private void tablaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseMoved
       int rowIndex = tabla.rowAtPoint(evt.getPoint());
       int colIndex = tabla.columnAtPoint(evt.getPoint());
       tabla.setToolTipText("<html>\n" +
            "<div style=\"width:200;\">"+(String)tabla.getValueAt(rowIndex, colIndex)+"</div>\n" +
            "\n" +
            "</html>");
    }//GEN-LAST:event_tablaMouseMoved

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if(tabla.getSelectedRowCount()!=0){
            jLabel4.setText("");
        }else{
           jLabel4.setText("Por favor seleccione un registro."); 
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_Programas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_Programas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_Programas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_Programas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                A_Programas dialog = new A_Programas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public static DefaultTableModel modelo;
     private void CrearModelo(){
         try {
             modelo = (new DefaultTableModel(
                null, new String [] {
                "id","Programa"}){
                Class[] types = new Class [] {
                java.lang.String.class,
                java.lang.String.class
                };
                boolean[] canEdit = new boolean [] {
                false,false
                };
                @Override
                public Class getColumnClass(int columnIndex) {
                   return types [columnIndex];
                }
                @Override
                public boolean isCellEditable(int rowIndex, int colIndex){
                   return canEdit [colIndex];
                }
            });
          tabla.setModel(modelo);
          Funciones_AD.ocultarColumnas(tabla, new int[] {0});
          tabla.getTableHeader().setReorderingAllowed(false);
          tabla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.toString()+" error");
            }     
        }
        public void Cargar_Programas(){
            try {
              Object M[]=null;
              int u=0;
              List<PypAdmProgramas> Programas;
              Programas=Declaraciones.Control_Programas_PYP.find_Programas();
                for (int i = 0; i < Programas.size(); i++) {
                    modelo.addRow(M);
                    modelo.setValueAt(Programas.get(i), u, 0);
                    modelo.setValueAt(Programas.get(i).getNombre(), u, 1);
                    u=u+1;
                }
             }catch (Exception e){
               JOptionPane.showMessageDialog(null, e.getMessage()); 
            }
        }
        public void Clear_Table1(){
        for (int i = 0; i < tabla.getRowCount(); i++) {
           modelo.removeRow(i);
           i-=1;
       }
      }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
